version: 1.2.1.{build}
branches:
  except: [/spike.*/]
environment:
  NugetPushKey:
    secure: Fr6Et35ii82/P5ZjfsKoIomda8gim+SKJkklwChGm5Jm2+wd/5uyQYbwAP4M7UTv
cache:
  - packages
  - Src\SerializationInspections.Plugin.Tests\Packages
artifacts:
  - path: Build\Output\TestCoverage
install:
  - git submodule update --init --recursive
build_script:
  - powershell -Command "& Build\Build.ps1 -Configuration Release -Version %APPVEYOR_BUILD_VERSION% -NugetPushKey %NugetPushKey%"

test: off
deploy: off
