version: 1.4.0.{build}
branches:
  except: [/spike.*/]
environment:
  NugetPushKey:
    secure: Fr6Et35ii82/P5ZjfsKoIomda8gim+SKJkklwChGm5Jm2+wd/5uyQYbwAP4M7UTv
  CoverageBadgeUploadToken:
    secure: /NFXyIKW45Q39yQFvB+0aJ1xGynLzg2bdJYDCyhhLH1l718N0vB1qt42hVxdv4GCGleHV4wHy1Efj1xNdNANpKlxPP/yrJrKtBLCYuEciAU=
cache:
  - packages -> **\packages.config
  - Src\SerializationInspections.Plugin.Tests\Packages
artifacts:
  - path: Build\Output\TestCoverage
install:
  - git submodule update --init --recursive
build_script:
  - powershell -Command "& Build\Build.ps1 -Configuration 'Release' -Version '%APPVEYOR_BUILD_VERSION%' -BranchName '%APPVEYOR_REPO_BRANCH%' -CoverageBadgeUploadToken '%CoverageBadgeUploadToken%' -NugetPushKey '%NugetPushKey%'"

test: off
deploy: off
