version: 1.7.0.{build}
branches:
  except: [/spike.*/]
image: Visual Studio 2017
environment:
  NugetPushKey:
    secure: Fr6Et35ii82/P5ZjfsKoIomda8gim+SKJkklwChGm5Jm2+wd/5uyQYbwAP4M7UTv
  CoverageBadgeUploadToken:
    secure: /NFXyIKW45Q39yQFvB+0aJ1xGynLzg2bdJYDCyhhLH1l718N0vB1qt42hVxdv4GCGleHV4wHy1Efj1xNdNANpKlxPP/yrJrKtBLCYuEciAU=
artifacts:
  - path: Build\Output\TestCoverage
  - path: Build\Output\TestCoverage\Summary.mht
  - path: Build\Output\*.nupkg
install:
  - git submodule update --init --recursive
build_script:
  - powershell -Command "& Build\Build.ps1 -Configuration 'Release' -Version '%APPVEYOR_BUILD_VERSION%' -BranchName '%APPVEYOR_REPO_BRANCH%' -CoverageBadgeUploadToken '%CoverageBadgeUploadToken%' -NugetPushKey '%NugetPushKey%'"

test: off
deploy: off
